[package]
name = "math-optim-verify"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"

[dependencies]
data-strux = { git = "https://github.com/chiaoicchi/math-optim-rs", subdirectory = "crates/data-strux" }
